routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('root');



/*=============================================================
=            ROTAS DO LARAVEL PARA GESTÃO DE LOGIN            =
=============================================================*/

    //Auth::routes();

    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register');

    Route::group(['prefix' => 'password'], function (){
        // Password Reset Routes...
        Route::get('/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('/reset', 'Auth\ResetPasswordController@reset');
    });

/*=====  End of ROTAS DO LARAVEL PARA GESTÃO DE LOGIN  ======*/




/*=======================================================
=            ROTAS PARA O TESTE BOA DIVERSÃO            =
=======================================================*/

    Route::group(['middleware' => 'auth'], function (){
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/teste', 'HomeController@index')->name('home_teste');

        Route::resource('/setor', 'SetorController');
        Route::resource('/sexo', 'SexoController');
        Route::resource('/lote', 'LoteController');
        Route::resource('/entrada', 'EntradaController');

        Route::resource('/ingresso', 'IngressoController');
        Route::resource('/registro', 'RegistroController');

    });

/*=====  End of ROTAS PARA O TESTE BOA DIVERSÃO  ======*/

app/Models/Sexo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Sexo extends Model
{
    protected $fillable = [
        'sexo'
    ];
}

app/Http/Controllers/SexoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Sexo;

class SexoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Obtendo todos os elementos do banco de dados
        $sexos = Sexo::all();

        // redirecionando para a view após a inserção do registro
        return view("sexo.index", ["sexos" => $sexos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // redirecionando para a view para inserção das informações
        return view("sexo.element");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Obtendo informação do formulário
        $sexoInput = $request->input("sexo");

        // Inserindo no bando de dados
        $insert = Sexo::create(['sexo' => $sexoInput]);

        // redirecionando para a view após a inserção do registro
        if ($insert)
            return redirect()->route("sexo.index", ["success" => "Sexo cadastrado com sucesso"]);
        else
            return redirect()->route("sexo.index", ["error" => "Oopz: Erro ao cadastrar sexo."]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // Obtendo o registro pelo ID
        $sexo = Sexo::find($id);

        // redirecionando para a view após a recuperação do registro
        return view("sexo.element", ['sexo' => $sexo]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Obtendo o registro pelo ID
        $sexo = Sexo::find($id);

        // Obtendo informação do formulário
        $sexoInput = $request->input("sexo");

        // Inserindo no bando de dados
        $update = $sexo->update(['sexo' => $sexoInput]);

        // redirecionando para a view após a edição do registro
        if ($update)
            return redirect()->route("sexo.index", ["success" => "Sexo alterado com sucesso"]);
        else
            return redirect()->route("sexo.index", ["error" => "Oopz: Erro ao alterar sexo."]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/sexo/element.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Gerenciamento de Sexos</div>

                <div class="panel-body">

                    @if (isset($sexo) )
                        <form action="{{ route('sexo.update', $sexo->id) }}" method="POST" role="form">
                        {!! method_field('PUT') !!}
                    @else
                        <form action="{{ route('sexo.store') }}" method="POST" role="form">
                    @endif

                        {!! csrf_field() !!}

                        <div class="form-group">
                            <label for="">Sexo</label>
                            <input type="text" class="form-control" name="sexo" value="{{ $sexo->sexo or '' }}" required>
                        </div>

                        <button type="submit" class="btn btn-success">Enviar</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sexo/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Gerenciamento de Sexos <a href="{{ route('sexo.create') }}" class="btn btn-xs btn-success pull-right" alt="Adicionar" title="Adicionar"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Adicionar</a></div>

                <div class="panel-body">

                    @include('alertas')

                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th width="60">ID</th>
                                    <th>Sexo</th>
                                    <th width="80">Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($sexos as $sexo)
                                <tr>
                                    <td>{{ $sexo->id }}</td>
                                    <td>{{ $sexo->sexo }}</td>
                                    <td><a href="{{ route('sexo.edit', $sexo->id) }}" class="btn btn-sm btn-primary" alt="Editar" title="Editar"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection