routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('root');



/*=============================================================
=            ROTAS DO LARAVEL PARA GESTÃO DE LOGIN            =
=============================================================*/

    //Auth::routes();

    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register');

    Route::group(['prefix' => 'password'], function (){
        // Password Reset Routes...
        Route::get('/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('/reset', 'Auth\ResetPasswordController@reset');
    });

/*=====  End of ROTAS DO LARAVEL PARA GESTÃO DE LOGIN  ======*/




/*=======================================================
=            ROTAS PARA O TESTE BOA DIVERSÃO            =
=======================================================*/

    Route::group(['middleware' => 'auth'], function (){
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/teste', 'HomeController@index')->name('home_teste');

        Route::resource('/setor', 'SetorController');
        Route::resource('/sexo', 'SexoController');
        Route::resource('/lote', 'LoteController');
        Route::resource('/entrada', 'EntradaController');

        Route::resource('/ingresso', 'IngressoController');
        Route::resource('/registro', 'RegistroController');

    });

/*=====  End of ROTAS PARA O TESTE BOA DIVERSÃO  ======*/

app/Models/Ingresso.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Ingresso extends Model
{
    protected $fillable = [
        'setor_id', 'sexo_id', 'lote_id', 'entrada_id', 'valor'
    ];

    /**
     * Obtendo o registro do setor relacionado a este ingresso
     */
    public function setor()
    {
        return $this->belongsTo('App\Models\Setor');
    }

    /**
     * Obtendo o registro do sexo relacionado a este ingresso
     */
    public function sexo()
    {
        return $this->belongsTo('App\Models\Sexo');
    }

    /**
     * Obtendo o registro do lote relacionado a este ingresso
     */
    public function lote()
    {
        return $this->belongsTo('App\Models\Lote');
    }

    /**
     * Obtendo o registro do tipo de entrada relacionado a este ingresso
     */
    public function entrada()
    {
        return $this->belongsTo('App\Models\Entrada');
    }
}

app/Http/Controllers/IngressoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Ingresso;
use App\Models\Setor;
use App\Models\Sexo;
use App\Models\Lote;
use App\Models\Entrada;


class IngressoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Obtendo todos os elementos do banco de dados
        $ingressos = Ingresso::all();

        // redirecionando para a view após a inserção do registro
        return view("ingresso.index", compact("ingressos"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Obtendo todos os elementos do banco de dados
        $ingressos = Ingresso::all();
        $setores   = Setor::all();
        $sexos     = Sexo::all();
        $lotes     = Lote::all();
        $entradas  = Entrada::all();

        // redirecionando para a view para inserção das informações
        return view("ingresso.element", compact("setores", "sexos", "lotes", "entradas"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Obtendo informação do formulário
        $inputSetor   = $request->input("setor");
        $inputSexo    = $request->input("sexo");
        $inputLote    = $request->input("lote");
        $inputEntrada = $request->input("entrada");
        $inputValor   = $request->input("valor");

        // Inserindo no bando de dados
        $insert = Ingresso::create([
            "setor_id"   => $inputSetor,
            "sexo_id"    => $inputSexo,
            "lote_id"    => $inputLote,
            "entrada_id" => $inputEntrada,
            "valor"      => $inputValor
        ]);

        // redirecionando para a view após a inserção do registro
        if ($insert)
            return redirect()->route("ingresso.index", ["success" => "Ingresso cadastrado com sucesso"]);
        else
            return redirect()->route("ingresso.index", ["error" => "Oopz: Erro ao cadastrar ingresso."]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // Obtendo o registro pelo ID
        $ingresso = Ingresso::find($id);

        // Obtendo todos os elementos do banco de dados
        $ingressos = Ingresso::all();
        $setores   = Setor::all();
        $sexos     = Sexo::all();
        $lotes     = Lote::all();
        $entradas  = Entrada::all();

        // redirecionando para a view após a recuperação do registro
        return view("ingresso.element", compact("ingresso", "setores", "sexos", "lotes", "entradas"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Obtendo o registro pelo ID
        $ingresso = Ingresso::find($id);

        // Obtendo informação do formulário
        $inputSetor   = $request->input("setor");
        $inputSexo    = $request->input("sexo");
        $inputLote    = $request->input("lote");
        $inputEntrada = $request->input("entrada");
        $inputValor   = $request->input("valor");

        // Inserindo no bando de dados
        $update = $ingresso->update([
            "setor_id"   => $inputSetor,
            "sexo_id"    => $inputSexo,
            "lote_id"    => $inputLote,
            "entrada_id" => $inputEntrada,
            "valor"      => $inputValor
        ]);

        // redirecionando para a view após a edição do registro
        if ($update)
            return redirect()->route("ingresso.index", ["success" => "Lote alterado com sucesso"]);
        else
            return redirect()->route("ingresso.index", ["error" => "Oopz: Erro ao alterar lote."]);

    }
}

resources/views/ingresso/element.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Gerenciamento de Ingressos</div>

                <div class="panel-body">

                    @if (isset($ingresso) )
                        <form action="{{ route('ingresso.update', $ingresso->id) }}" method="POST" role="form">
                        {!! method_field('PUT') !!}
                    @else
                        <form action="{{ route('ingresso.store') }}" method="POST" role="form">
                    @endif

                        {!! csrf_field() !!}

                        <div class="row">
                            <div class="col-xs-12 col-sm-6">
                                <div class="form-group">
                                    <label for="">Setor</label>
                                    <!-- <input type="text" class="form-control" name="ingresso" value="{{ $ingresso->ingresso or '' }}" required> -->
                                    <select class="form-control" name="setor" required>
                                        <option value=""></option>
                                        @foreach ($setores as $setor)
                                            <option value="{{ $setor->id }}" {{ (isset($ingresso) && $ingresso->setor_id == $setor->id ? "selected":"") }}>{{ $setor->setor }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6">
                                <div class="form-group">
                                    <label for="">Sexo</label>
                                    <!-- <input type="text" class="form-control" name="ingresso" value="{{ $ingresso->ingresso or '' }}" required> -->
                                    <select class="form-control" name="sexo" required>
                                        <option value=""></option>
                                        @foreach ($sexos as $sexo)
                                            <option value="{{ $sexo->id }}" {{ (isset($ingresso) && $ingresso->sexo_id == $sexo->id ? "selected":"") }}>{{ $sexo->sexo }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-12 col-sm-6">
                                <div class="form-group">
                                    <label for="">Lote</label>
                                    <!-- <input type="text" class="form-control" name="ingresso" value="{{ $ingresso->ingresso or '' }}" required> -->
                                    <select class="form-control" name="lote" required>
                                        <option value=""></option>
                                        @foreach ($lotes as $lote)
                                            <option value="{{ $lote->id }}" {{ (isset($ingresso) && $ingresso->lote_id == $lote->id ? "selected":"") }}>{{ $lote->lote }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6">
                                <div class="form-group">
                                    <label for="">Entrada</label>
                                    <!-- <input type="text" class="form-control" name="ingresso" value="{{ $ingresso->ingresso or '' }}" required> -->
                                    <select class="form-control" name="entrada" required>
                                        <option value=""></option>
                                        @foreach ($entradas as $entrada)
                                            <option value="{{ $entrada->id }}" {{ (isset($ingresso) && $ingresso->entrada_id == $entrada->id ? "selected":"") }}>{{ $entrada->entrada }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-12 col-sm-6">
                                <div class="form-group">
                                    <label for="">Valor</label>
                                    <input type="number" min="0.00" max="10000.00" step="0.50" class="form-control" name="valor" value="{{ $ingresso->valor or '0.00' }}" required>
                                </div>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-success">Enviar</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/ingresso/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Gerenciamento de Ingressos <a href="{{ route('ingresso.create') }}" class="btn btn-xs btn-success pull-right" alt="Adicionar" title="Adicionar"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Adicionar</a></div>

                <div class="panel-body">

                    @include('alertas')

                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th width="60">ID</th>
                                    <!-- <th>Ingresso</th> -->
                                    <th>Setor</th>
                                    <th>Sexo</th>
                                    <th>Lote</th>
                                    <th>Tipo de Entrada</th>
                                    <th>Valor</th>
                                    <th width="60">Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($ingressos as $ingresso)
                                <tr>
                                    <td>{{ $ingresso->id }}</td>
                                    <!-- <td>{{ $ingresso->ingresso }}</td> -->
                                    <td>{{ $ingresso->setor->setor }}</td>
                                    <td>{{ $ingresso->sexo->sexo }}</td>
                                    <td>{{ $ingresso->lote->lote }}</td>
                                    <td>{{ $ingresso->entrada->entrada }}</td>
                                    <td>{{  'R$ '.number_format($ingresso->valor, 2, ',', '.') }}</td>
                                    <td><a href="{{ route('ingresso.edit', $ingresso->id) }}" class="btn btn-sm btn-primary" alt="Editar" title="Editar"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection